services:
  postgres:
    image: postgres:15-alpine
    container_name: rao_postgres
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - is_rao_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    ports:
      - "2302:5432"
    networks:
      - rao_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  # PgAdmin для управления PostgreSQL
  is-rao-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: is-rao-pgadmin
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped
    ports:
      - "2303:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
      TZ: ${TZ}
    volumes:
      - is-rao-pgadmin-data:/var/lib/pgadmin
      - is-rao-pgadminlogs:/var/log/pgadmin
      - /pgadmin_config.py:/pgadmin4/config_local.py:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - rao_network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "--timeout=10",
          "--quiet",
          "http://localhost/",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  rao_api:
    build: .
    env_file:
      - .env
    container_name: rao_api
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      API_URL: ${API_ACCESS}
      PYTHONPATH: /app
      UVICORN_TIMEOUT: 1200
      PYTHONUNBUFFERED: 1
      TZ: ${TZ}
    depends_on:
      - postgres
    ports:
      - "2300:20142"
    volumes:
      - .:/app
      - /tmp:/tmp
    command: uvicorn main:app --host 0.0.0.0 --port 20142 --timeout-keep-alive 1200 --timeout-graceful-shutdown 600 --reload
    restart: unless-stopped
    networks:
      - rao_network

  redis:
    image: redis:7-alpine
    container_name: rao_redis
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # ports:
    #   - "6379:6379"
    networks:
      - rao_network
    volumes:
      - is_rao_redis_data:/data
    restart: unless-stopped

  celery_worker:
    build: .
    env_file:
      - .env
    container_name: rao_celery_worker
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - .:/app
      - /tmp:/tmp
    environment:
      - REDIS_URL=redis://rao_redis:6379/0
      - CELERY_BROKER_URL=redis://rao_redis:6379/0  # Добавьте это
      - CELERY_RESULT_BACKEND=redis://rao_redis:6379/0  # Добавьте это
      - TZ=${TZ}
      - API_KEY=${API_KEY}
    depends_on:
      - redis
    networks:
      - rao_network
    command: celery -A celery_app worker -E --pool=solo --loglevel=info --concurrency=4 -Q evaluation,parsing,scoring
    restart: unless-stopped

  celery_beat:
    build: .
    env_file:
      - .env
    container_name: rao_celery_beat
    dns:
      - 8.8.8.8
      - 1.1.1.1
    command: celery -A celery_app beat --loglevel=info
    volumes:
      - .:/app
      - /tmp:/tmp
    environment:
      - REDIS_URL=redis://rao_redis:6379/0
      - CELERY_BROKER_URL=redis://rao_redis:6379/0  # Добавьте это
      - CELERY_RESULT_BACKEND=redis://rao_redis:6379/0  # Добавьте это
      - TZ=${TZ}
      - API_KEY=${API_KEY}
    depends_on:
      - redis
    networks:
      - rao_network
    restart: unless-stopped

  flower:
    build: .
    container_name: rao_flower
    dns:
      - 8.8.8.8
      - 1.1.1.1
    command: celery -A celery_app flower --port=5555 --inspect-timeout=10000
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://rao_redis:6379/0
      - CELERY_BROKER_URL=redis://rao_redis:6379/0  # Добавьте это
      - CELERY_RESULT_BACKEND=redis://rao_redis:6379/0  # Добавьте это
      - TZ=${TZ}     
    depends_on:
      - redis
      - celery_worker
    networks:
      - rao_network
    restart: unless-stopped

networks:
  rao_network:
    external: false

volumes:
  is_rao_postgres_data:
  is_rao_redis_data:
  is-rao-pgadmin-data:
  is-rao-pgadminlogs: