-- Таблица для хранения извлечённых "сырых" данных из документов (соответствует report_for_operator)
CREATE TABLE raw_document_data (
    procurement_id SERIAL PRIMARY KEY,
    expertise_object JSONB,
    legal_regulation JSONB,
    procurement_method JSONB,
    expertise_request JSONB,
    acceptance_act JSONB,
    contract_date DATE,
    works_acceptance_doc JSONB,
    goods_acceptance_doc JSONB,
    impossible_alternative_doc JSONB,
    penalty_recovery_docs JSONB,
    warranty_docs JSONB,
    contract_conditions_docs JSONB,
    ip_rights_transfer_docs JSONB,
    goods_origin_docs JSONB,
    additional_materials JSONB,
    contract_amendments JSONB,
    notice JSONB,
    nir_contract JSONB,
    service_contract JSONB,
    goods_contract JSONB,
    price_justification_docs JSONB,
    price_justification JSONB,
    procurement_description JSONB,
    nir_report JSONB,
    procurement_policy JSONB,
    bid_evaluation_procedure JSONB,
    contract_subject JSONB,
    contract_draft JSONB,
    contract_details JSONB,
    compliance_certificates JSONB,
    eis_link JSONB,
    technical_documentation JSONB,
    goods_invoice JSONB,
    bid_requirements JSONB,
    work_results_photos JSONB,
    goods_photos JSONB,
    contract_execution_expertise JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Таблица для хранения итогового "чистого" заключения модели (соответствует report_for_operator)
CREATE TABLE clean_document_conclusions (
    procurement_id SERIAL PRIMARY KEY,
    expertise_object TEXT,
    legal_regulation TEXT,
    procurement_method TEXT,
    expertise_request TEXT,
    acceptance_act TEXT,
    contract_date DATE,
    works_acceptance_doc TEXT,
    goods_acceptance_doc TEXT,
    impossible_alternative_doc TEXT,
    penalty_recovery_docs TEXT,
    warranty_docs TEXT,
    contract_conditions_docs TEXT,
    ip_rights_transfer_docs TEXT,
    goods_origin_docs TEXT,
    additional_materials TEXT,
    contract_amendments TEXT,
    notice TEXT,
    nir_contract TEXT,
    service_contract TEXT,
    goods_contract TEXT,
    price_justification_docs TEXT,
    price_justification TEXT,
    procurement_description TEXT,
    nir_report TEXT,
    procurement_policy TEXT,
    bid_evaluation_procedure TEXT,
    contract_subject TEXT,
    contract_draft TEXT,
    contract_details TEXT,
    compliance_certificates TEXT,
    eis_link TEXT,
    technical_documentation TEXT,
    goods_invoice TEXT,
    bid_requirements TEXT,
    work_results_photos TEXT,
    goods_photos TEXT,
    contract_execution_expertise TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Индексы для производительности
CREATE INDEX idx_raw_procurement_id ON raw_document_data (procurement_id);
CREATE INDEX idx_clean_procurement_id ON clean_document_conclusions (procurement_id);